version: '2'
services:

  static:
    build: ./app/
    container_name: static
    ports:
     - 7001:8080
  
  nodejs:
    build: ./server/
    container_name: nodejs
    ports:
      - 4000:3000

  db:
    # image: mysql:5.6
    # container_name: db
    build: ./mysql/
    container_name: mysql
    # environment:
    #   MYSQL_ROOT_PASSWORD: "123456"
    # command:
    #   --default-authentication-plugin=mysql_native_password
    #   --character-set-server=utf8mb4
    
    ports:
      - 3308:3306
    