version: '2'
services:

  static:
    build: ./app/
    ports:
     - 7001:8080
  
  nodejs:
    build: ./server/
    ports:
      - 4000:3000

  db:
    image: mysql:5.6
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    
    ports:
      - 3308:3306
  